site_name: test-actions
site_url: https://fast-microscopy.github.io/test-actions/
site_description: A toolbox for registering / fusing / stitching multi-view / multi-positioning image datasets in 2-3D.

repo_name: test-actions
repo_url: https://github.com/fast-microscopy/test-actions/
# edit_uri: edit/main/docs/
# use_directory_urls: false

plugins:
  - mike:
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
            paths: [src]

nav:
  - index.md

theme:
  name: "material"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.footer  # next/previous links in footer
  icon:
    logo: fontawesome/solid/clone
    repo: fontawesome/brands/github
  favicon:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

extra:
  version:
    provider: mike
    default: main
    
